
# .github/workflows/build-white-label.yml
name: White-Label Build

on:
  push:
    branches: [ main ]

jobs:
  fetch-flavors:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.flavors.outputs.flavors }}
    steps:
      - uses: actions/checkout@v4

      - name: Fetch flavors
        id: flavors
        uses: lucianosantosdev/prisme-fetch-flavors-action@v0.1
        with:
          project-api-key: ${{ secrets.PRISME_API_KEY }}

      - name: Print flavors
        run: echo "${{ steps.flavors.outputs.flavors }}"

  build-flavors:
    name: Build '${{ matrix.name }}'
    needs: fetch-flavors
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.fetch-flavors.outputs.matrix) }}
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Apply branding
        uses: lucianosantosdev/prisme-apply-flavor-action@v0.1
        with:
          project-api-key: ${{ secrets.PRISME_API_KEY }}
          flavor: ${{ toJson(matrix) }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run build
        run: ./gradlew build

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.name }}.apk
          path: '**/outputs/**/*.apk'