
# .github/workflows/build-white-label.yml
name: White-Label Build

on:
  push:
    branches: [ main ]

jobs:
  fetch-flavors:
    runs-on: ubuntu-latest
    outputs:
      flavors: ${{ steps.fetch-flavors-action.outputs.flavors }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Fetch flavors
        id: fetch-flavors-action
        uses: FlavorFlow-io/fetch-flavors-action@v1
        with:
          project-api-key: ${{ secrets.FLAVORFLOW_API_KEY }}

  build-flavors:
    name: Build '${{ matrix.name }}'
    needs: fetch-flavors
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(needs.fetch-flavors.outputs.flavors).flavors }}
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Apply branding
        uses: ./.github/actions/apply-flavor-action
        with:
          project-api-key: ${{ secrets.FLAVORFLOW_API_KEY }}
          flavor: ${{ toJson(matrix) }}
          project-type: 'android-native-compose'
      
      - name: Print environment variables
        run: |
          echo "=============="
          env
          echo "=============="
          echo $FLAVORFLOW_LOGO
          echo "=============="
          cat "$FLAVORFLOW_LOGO"
          exit 1

      - uses: actions/setup-java@v4
        with:
          distribution: 'jetbrains'
          java-version: '21'
          
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Run build
        run: ./gradlew build

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.name }}.apk
          path: '**/outputs/**/*.apk'